# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('cataory', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
