# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userinfo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uva', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='onlinejudgeid',
            name='user',
        ),
        migrations.DeleteModel(
            name='onlinejudgeid',
        ),
    ]
