# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0002_problemset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='id',
        ),
        migrations.AlterField(
            model_name='problemset',
            name='number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
