# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Helper', '0002_auto_20180809_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='section', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
            ],
        ),
    ]
