# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0004_auto_20180911_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemset',
            old_name='catagory',
            new_name='category',
        ),
    ]
