# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0006_auto_20180918_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
