# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Helper', '0007_problemset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Helper.problemset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
