# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0009_auto_20181027_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
